language: python

os:
  - linux

python: 
  - "3.9"

install:
  - pip install -r requirements.txt

script:
  - coverage run --source='.' manage.py test .
  - python manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .coverage